### ISSUE TITLE
Usman L02E06

### ISSUE THREAD

**Issue by UsmanIjaz** [udacity/robotics-beta-test-issues#41] opened 2017-04-19 00:48 UTC
Avideo with an example of perspective transform should be added as it was done in SDCND. 
A very good and detailed example can be seen here https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/40ec78ee-fb7c-4b53-94a8-028c5c60b858/concepts/d33ae3ea-01aa-414e-ad20-208dc161793d

**Comment by ryan-keenan** [comment] 2017-04-22 20:46
Will do thanks!

**Comment by ryan-keenan** [comment] 2017-05-01 05:50
closing as this is a duplicate of #37

**Closed as completed by ryan-keenan** 2017-05-01 05:50 UTC
