### ISSUE TITLE
arek - Project 2 - Running ./safe_spawner.sh getting [ERROR] Found empty JointState message

### ISSUE THREAD

**Issue by 867sec** [udacity/robotics-beta-test-issues#524] opened 2017-07-04 04:23 UTC
arek - Project 2: When running `./safe_spawner.sh` in both demo `true` and demo `false` modes... Every time the "Next" button is pressed getting the following error and cannot find any documentation about it... It happens every time in both VM 2.0.1 and 2.1.0 beta (freshly downloaded after following directions in Project 2 "Setting up your environment" lesson. Screenshot attached below. [ERROR] Found empty JointState message
![screen shot 2017-07-03 at 02 26 25](https://user-images.githubusercontent.com/28066540/27815035-1b834e20-604f-11e7-954e-96d6ad636230.png)

**Comment by sahiljuneja** [comment] 2017-07-04 04:51
Since this is an isolated case, my best recommendation right now is that you start on the process again of downloading the repo and everything for the project and repeating the steps properly to ensure you checked off everything. 

Secondly, if this happens when you run the IK_server script, then it's quite possible you are not returning the correct values (or format) or there's some issue with your code somewhere, maybe? Share your script with the code with me on the course Slack, and I will try to see if I can reproduce the error on my end. 

But do try to redo the process without missing out on a step. Often there's something we end up missing out on which can cause these errors!

**Comment by 867sec** [comment] 2017-07-04 05:22
This problem happens when running ./safe_spawner.sh not IK_server.py.
This problem happens on freshly downloaded VM version 2.0.1 or 2.1.0 after
following instructions in the "Setting up your environment" section of
lesson Project 2.
When you say: "repeating the steps properly to ensure you checked off
everything" please be specific. Do you mean the steps in the "Setting up
your environment" section of lesson Project 2 (which I did) or something
else?

**Comment by hvpandya** [comment] 2017-07-22 19:31
This is a benign issue related to a specific commit on moveit's kinetic-devel branch.

Since this is an isolated case and the errors do not affect the project in any manner other than being annoying, I am closing this issue.

More info: http://answers.ros.org/question/266274/moveit-regression-found-empty-jointstate-message/

**Closed as completed by hvpandya** 2017-07-22 19:31 UTC
