### ISSUE TITLE
diyjac L05E06

### ISSUE THREAD

**Issue by diyjac** [udacity/robotics-beta-test-issues#298] opened 2017-05-15 15:01 UTC
```
rosnode list rosservice list
```
should be:
```
rosnode list
rosservice list
```

I am unable to set the arm position using the command:
```
robo@robo-virtual-machine:~/catkin_ws$ rosservice call /arm_mover/safe_move "joint_1: 1.57 joint_2: 1.57"
```
It gives me the following error:
```
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/rosservice", line 35, in <module>
    rosservice.rosservicemain()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosservice/__init__.py", line 746, in rosservicemain
    _rosservice_cmd_call(argv)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosservice/__init__.py", line 607, in _rosservice_cmd_call
    service_args.append(yaml.load(arg))
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<string>", line 1, column 22:
    joint_1: 1.57 joint_2: 1.57
                         ^
```

This seems to send the message, but cannot see the arm moving in Gazebo.
```
rosservice call /arm_mover/safe_move '{"joint_1": 1.57, "joint_2": 1.57}'
```

**Comment by bkinman** [comment] 2017-05-23 23:22
Closing this as I am unable to reproduce.

Is it perhaps the case that you have some error message in your master console that could be telling?

I was able to run my initial command and have the arm move, I was also able to run the command you described as well.

**Comment by bkinman** [comment] 2017-05-23 23:22
Feel free to open this issue back up if you have more information.

**Closed as completed by bkinman** 2017-05-23 23:22 UTC
